data/urls.py
# Blanca Martin and Luis Carabe pair number 10

# workflowrepository URL Configuration

from django.conf.urls import url

urlpatterns = [
    url(r'^base/', views.base, name='base'),
]

find/urls.py
# Blanca Martin and Luis Carabe pair number 10

# workflowrepository URL Configuration

from django.conf.urls import url
from find import views


# All urls for workflow lists/search/detail
urlpatterns = [
    url(r'^$', views.workflow_list, name='workflow_list'),
    url(r'^workflow_list/(?P<category_slug>[-\w]+)/$', views.workflow_list, name='workflow_list_by_category'),
    url(r'^workflow_detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.workflow_detail, name='workflow_detail'),
    url(r'^workflow_search/(?P<name>[-\w]+)/$', views.workflow_search, name='workflow_search'),
    url(r'^workflow_search/$', views.workflow_search, name='workflow_search'),
    url(r'^workflow_download/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.workflow_download, name='workflow_download'),
    url(r'^workflow_download_json/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.workflow_download_json, name='workflow_download_json'),
]

upload/urls.py
# Blanca Martin and Luis Carabe pair number 10

# workflowrepository URL Configuration

from django.conf.urls import url
from upload import views as upload

urlpatterns = [
    url(r'^add_workflow/$', upload.add_workflow, name='add_workflow'),
]

workflowrepository/urls.py
# Blanca Martin and Luis Carabe pair number 10

# workflowrepository URL Configuration

from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from data import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^base/', views.base, name='base'),
    url(r'', include('find.urls')), # Include of urls defined in our app find
    url(r'', include('upload.urls', namespace='upload')), # Include of urls defined in our app upload

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

find/models.py
# Blanca Martin and Luis Carabe pair number 10

# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

find/views.py
# Blanca Martin and Luis Carabe pair number 10

# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
import django, os
import urllib
import urllib2

from django.shortcuts import render
from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.http import HttpResponse

from data.models import Category, Workflow
from workflowrepository import settings


def workflow_list(request, category_slug = None):
	page = request.GET.get('page', 1)
	workflows = None

	# Search for all categories
	categories = Category.objects.all()
	found = True # Default value of found is true

	# Check if we are searching a specific category
	# In case not...
	if category_slug == None:
		category = None
		# List of all workflows
		workflow_list = Workflow.objects.all()
		if workflow_list.count() == 0:
			found = False
			error = "No Workflows found!"
		else:
			# We paginate the workflow list making pages of 10 workflows
			paginator = Paginator(workflow_list, 10)
			error = ""
			try:
				workflows = paginator.page(page)
			except PageNotAnInteger:
				workflows = paginator.page(1)
			except EmptyPage:
				paginator = paginator.page(paginator.num_pages)
	# In other case...
	else:
		try:
			# Find category with that slug and its workflows
			category = Category.objects.get(slug = category_slug)
			workflow_list = Workflow.objects.filter(category = category)
			paginator = Paginator(workflow_list, 10)
		except ObjectDoesNotExist:
			# Category does not exist
			category = None
			found = False
			error = "Category with slug '" + category_slug + "' does not exist"

		# If there is no workflows in some category
		if workflow_list.count()==0 and found == True:
			found = False
			error = "No Workflows in this category!"
		else:
			found = True
			error = ""
			# We paginate the workflow list making pages of 10 workflows
			paginator = Paginator(workflow_list, 10)
			error = ""
			try:
				workflows = paginator.page(page)
			except PageNotAnInteger:
				workflows = paginator.page(1)
			except EmptyPage:
				paginator = paginator.page(paginator.num_pages)

	# Create the dictionary
	_dict = {'category' : category,
					 'categories' : categories,
					 'workflows' : workflows,
					 'result' : found,
					 'error' : error}
	return render(request, 'find/list.html', _dict)

def workflow_detail(request, id, slug):

	# Default values
	found = True
	error=""

	# Find workflow with id given
	try:
		workflow = Workflow.objects.get(id = id)
	except ObjectDoesNotExist:
		# Workflow does not exist
		workflow = None
		found = False
		error = "Workflow with slug '" + slug + "' and id '" + str(id) +  "' does not exist"

	# Create the dictionary
	_dict = {}
	_dict['result'] = found
	_dict['workflow'] = workflow
	_dict['error'] = error
	_dict['key'] = settings.SITE_KEY

	return render(request, 'find/detail.html', _dict)

def workflow_search(request):

	# Default values
	found = True
	error=""

	# Find workflow with name given
	try:
		workflow = Workflow.objects.get(name = request.POST['key'])
	except ObjectDoesNotExist:
		# Workflow does not exist
		workflow = None
		found = False
		error = "Workflow with name '" + request.POST['key'] + "' does not exist"

	# Create the dictionary
	_dict = {}
	_dict['result'] = found
	_dict['workflow'] = workflow
	_dict['error'] = error
	_dict['key'] = settings.SITE_KEY

	return render(request, 'find/detail.html', _dict)


def workflow_download(request, id, slug, count = True):

	# Begin reCAPTCHA validation 
	recaptcha_response = request.POST.get('g-recaptcha-response')
	url = 'https://www.google.com/recaptcha/api/siteverify'
	values = {
			'secret': settings.SECRET_KEY,
			'response': recaptcha_response
	}
	data = urllib.urlencode(values)
	req = urllib2.Request(url, data)
	response = urllib2.urlopen(req)
	result = json.load(response)
	# End reCAPTCHA validation 

	content = {}
	# If the reCAPTCHA validation gave an error,
	# an error message is shown informing of that.
	if not result['success']:
		content['result'] = False
		content['error'] = 'Invalid reCAPTCHA. Please try again.'
		content['key'] = settings.SITE_KEY
		return render(request, 'find/detail.html', content)

	# If the reCAPTCHA validation was successfull
	try:
		# The workflow with id = 'id' is search in the database
		workflow = Workflow.objects.get(id = id)
		# We add 1 to the downloads of that workflow
		workflow.downloads = workflow.downloads + 1

		# The content of the json is sent back to the user
		response = HttpResponse(workflow.json, content_type = 'application/octet-stream')
		filename = "outfile.json"
		response['Content-Disposition'] = 'inline; filename=%s' % filename
		return response

	except ObjectDoesNotExist:
		# If the workflow could not be found, nothing is done
		return None

def workflow_download_json(request, id, slug):
	try:
		# Search for the workflow with id = 'id'
		workflow = Workflow.objects.get(id = id)
		# The conetnt of the json is sent
		return HttpResponse(workflow.json, content_type = 'application/octet-stream')
	except ObjectDoesNotExist:
		# If the workflow could not be found, nothing is done
		return None

templates/find/detail.html
{% extends "../data/base.html" %}
{% load staticfiles %}


{% block scripts %}
	
	<!-- Load webcomponents support -->
	<script src="{% static 'js/webcomponents/webcomponents-loader.js' %}">
	</script>
	<!-- Load the recaptcha support -->
	<script src='https://www.google.com/recaptcha/api.js'></script>
	<!-- link the web component code -->
	<link rel="import" href="{% static 'scipion-workflow.html' %}">

{% endblock %}

<!-- If there is a result, workflow is not null, 
		so the title is the workflow's name -->
{% if result != False %}
	{% block title %}
		{{ workflow.name }}
	{% endblock %}
{% endif %}

<!-- Main body -->
{% block content %}
	<div id="main">
		<h2>{{ error }}</h2> <br>
		<span class="row">
			<!-- If there is a result, the content is
			     the workflow information  -->
			{% if result != False %}

				<div id="info">
					<!-- Workflow name -->
					<h2>{{workflow.name}}</h2>
					<!-- Workflow categories -->
					{% for cat in workflow.category.all %}
						<a href="{% url 'workflow_list_by_category' cat.slug %}">{{ cat.name }}</a><br>
					{% endfor %}
					<!-- Workflow keywords -->
					<b>KeyWords:</b>{{workflow.keywords}}<br>
					<!-- Workflow description -->
					<b>Description:</b>{{workflow.description}}

					<!-- Form for the download of the workflow -->
					<form action="{% url 'workflow_download' workflow.id workflow.slug %}" method="post">
						{% csrf_token %}
						<!-- recaptcha -->
				    <div class="g-recaptcha" data-sitekey="{{key}}"></div>
				    <!-- button -->
						<input type="submit" name="submit" value="Download">
					</form>
				</div>
				<!-- Division with the workflow's json -->
				<div id="scipion">
					<scipion-workflow src="{% url 'workflow_download_json' workflow.id workflow.slug %}" height="400px" width="400px"/>
				</div>
			<!-- If there was no result, an error message is shown -->
			{% else %}
				<h2>The workflow could not be found.</h2>
		</span>
	</div>
	{% endif %}
{% endblock %}

templates/find/list.html
{% extends "../data/base.html" %}

<!-- If we are listing the workflows of a 
		 given category, the title is the category's name -->
{% if category %}
	{% block title %}
		{{ category.name }}
	{% endblock %}
{% endif %}

{% block content %}
	<div class="row">
	<!-- Sidebar containing the names of all the categories -->
		<div id="sidebar">
			<h2>Categories</h2>
				<a href="{% url 'workflow_list' %}">All </a><br>
			{% for cat in categories %}
					<a href="{% url 'workflow_list_by_category' cat.slug %}">{{ cat.name }}</a><br>
			{% endfor %}
			<a href="{% url 'upload:add_workflow' %}">Upload Workflow</a>
		</div>

		<div id="main">
			<!-- If we are listling the workflows of a category, 
					 we name that category -->
			{% if category %}
				<div>
					<h1>{{ category.name }}</h1>
				<!-- If not, we are just listing all the workflows -->
				{% else %}
					<h1>Workflows</h1>
				{% endif %}
				<!-- If there are workflows, in the category or in the db
				     we print their name and description -->
				{% if result %}
					<div>
						{% for w in workflows %}
							<a href="{% url 'workflow_detail' w.id w.slug %}">{{w.name}}</a>:{{w.description | truncatechars:255}}<br>
						{% endfor %}
					</div>
				<!-- For the pagination -->
					{% if workflows.has_other_pages %}
				  <ul class="pagination" style="float: left;">
				    {% if workflows.has_previous %}
				      <li><a href="?page={{ workflows.previous_page_number }}">&laquo;</a></li>
				    {% else %}
				      <li class="disabled"><span>&laquo;</span></li>
				    {% endif %}
				    {% for i in workflows.paginator.page_range %}
				      {% if workflows.number == i %}
				        <li class="pure-menu-active"><span>{{ i }}</span></li>
				      {% else %}
				        <li class="pure-menu"><a href="?page={{ i }}">{{ i }}</a></li>
				      {% endif %}
				    {% endfor %}
				    {% if workflows.has_next %}
				      <li><a href="?page={{ workflows.next_page_number }}">&raquo;</a></li>
				    {% else %}
				      <li class="disabled"><span>&raquo;</span></li>
				    {% endif %}
				  </ul>
				
				</div>
				<!-- If not, an error message is shown -->
				{% else %}
					{{error}}
			{% endif %}
		
	</div>

</div>
{% endif %}

{% endblock %}